export const brands = [
  'Missha',
  'Medi Peel',
  'Farm Stay',
  'Masil',
  'Moremo',
  'Daeng Gi Meo Ri',
  'Dr.Jart + ',
  'Innisfree',
  'Eyenlip',
  'Valmona',
  'HOLIKA HOLIKA',
  'Ellips',
  'Bathpa',
  'Kiss by Rosemine',
  'Too Cool For School',
  'Bueno',
  'Jennyhouse',
  'Etude House',
  'The Ordinary',
  'Jigott',
  'Lador',
  'Naturia',
];
