export const NavLinks = [
  {
    key: 'face',
    title: 'Догляд за обличчям',
    hiddenNavLinks: [
      { 'makeup-removal': 'Зняття макіяжу' },
      { 'skin-cleansing': 'Очищення шкіри' },
      { peeling: 'Пілінг' },
      { toning: 'Тонізація' },
      {
        'enhanced-care':
          'Посилений догляд ( сиворотки, ампули , есенції , емульсії )',
      },
      { 'face-cream': 'Крем для обличчя ' },
      { 'eye-cream': 'Крем навколо очей' },
      { 'neck-care': 'Догляд за зоною декольте' },
      { mask: 'Маска ( нічні або тканинні доглядові )' },
      { 'sun-protection': 'Cонцезахист' },
      { 'lip-care': 'Догляд для губ' },
    ],
  },
  {
    key: 'hair',
    title: 'Волосся',
    hiddenNavLinks: [
      { shampoo: 'Шампунь' },
      { 'scalp-scrub': 'Скраб для шкіри голови' },
      { mask: 'Маска' },
      { balm: 'Бальзам' },
      { 'essences-emulsions-vitamins': 'Есенції , емульсії , вітаміни' },
      { 'thermal-protection': 'Термозахист' },
    ],
  },
  {
    key: 'body',
    title: 'Тіло',
    hiddenNavLinks: [
      { 'shower-gel': 'Гель для душу ' },
      { 'body-scrub': 'Скраб для тіла' },
      { 'anti-cellulite': 'Антицелюлітні засоби' },
      { 'lotions-oils-care-cream': 'Лосьйони, масла, крем догляд' },
      { 'sun-protection': 'Сонцезахист' },
    ],
  },
  { key: 'tone', title: 'Підбір тональних засобів' },
  {
    key: 'brands',
    title: 'Бренди',
    hiddenNavLinks: [
      'Missha',
      'Medi Peel',
      'Farm Stay',
      'Masil',
      'Moremo',
      'Daeng Gi Meo Ri',
      'Dr.Jart + ',
      'Innisfree',
      'Eyenlip',
      'Valmona',
      'HOLIKA HOLIKA',
      'Ellips',
      'Bathpa',
      'Kiss by Rosemine',
      'Too Cool For School',
      'Bueno',
      'Jennyhouse',
      'Etude House',
      'The Ordinary',
      'Jigott',
      'Lador',
      'Naturia',
    ],
  },
  { key: 'novelty', title: 'Новинки' },
];
