export const NavLinks = [
  {
    key: 'face',
    title: 'Догляд за обличчям',
    hiddenNavLinks: [
      'Зняття макіяжу',
      'Очищення шкіри',
      'Пілінг',
      'Тонізація',
      'Посилений догляд ( сиворотки, ампули , есенції , емульсії )',
      'Крем для обличчя ',
      'Крем навколо очей',
      'Догляд за зоною декольте',
      'Маска ( нічні або тканинні доглядові )',
      'Cонцезахист',
      'Догляд для губ',
    ],
  },
  {
    key: 'hair',
    title: 'Волосся',
    hiddenNavLinks: [
      'Шампунь',
      'Скраб для шкіри голови',
      'Маска',
      'Бальзам',
      'Есенції , емульсії , вітаміни',
      'Термозахист',
    ],
  },
  {
    key: 'body',
    title: 'Тіло',
    hiddenNavLinks: [
      'Гель для душу ',
      'Скраб для тіла',
      'Антицелюлітні засоби',
      'Лосьйони, масла, крем догляд',
      'Сонцезахист',
    ],
  },
  { key: 'tone', title: 'Підбір тональних засобів' },
  {
    key: 'brands',
    title: 'Бренди',
    hiddenNavLinks: [
      'Missha',
      'Medi Peel',
      'Farm Stay',
      'Masil',
      'Moremo',
      'Daeng Gi Meo Ri',
      'Dr.Jart + ',
      'Innisfree',
      'Eyenlip',
      'Valmona',
      'HOLIKA HOLIKA',
      'Ellips',
      'Bathpa',
      'Kiss by Rosemine',
      'Too Cool For School',
      'Bueno',
      'Jennyhouse',
      'Etude House',
      'The Ordinary',
      'Jigott',
      'Lador',
      'Naturia',
    ],
  },
  { key: 'novelty', title: 'Новинки' },
];
